name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # раз в день
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: massonsky
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: false
          config_timezone: Europe/Moscow
          languages: true
          languages_limit: 8
          languages_colors: github
          languages_threshold: 0%
          plugins_achievements: true
          plugins_achievements_threshold: C
          plugins_achievements_secrets: true
          plugins_achievements_display: compact
          plugin_lines: true